Option Strict On
Option Explicit On 

Namespace DragD

Namespace QuickWhereComponent

	Public Interface IWhereEntity

		' Generates SQL WHERE clause without the keyword 'WHERE'
		Function GetSql() As String



		' Returns value that determines whether the WHERE clause
		' generated by GetSql() is empty string

		' A WhereItem would be Idle when:
		' 1) the property FieldName returns blank and/or 
		' 2) the properties Value and Value 2 are blank
		' WithValues parameter determines whether the Value and Value2 should be examined

		' A WhereClause and QuickWhere would be Idle when all
		' contained WhereClauses and/or WhereItems are Idle
		Function Idle(Optional ByVal WithValues As Boolean = False) As Boolean



		' Determines whether the IWhereEntiry should be included into the
		' WHERE clause generated by GetSql()
		Property Used() As Boolean


	End Interface

End Namespace

End Namespace